# BEGIN_KITTY_THEME
include Matugen.conf
# END_KITTY_THEME
#

# Fonts
font_family Profont Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 10

# Cursors
cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval -1
mouse_hide_wait 1.0

# Hyperlinks
underline_hyperlinks hover

# Opacity
dynamic_background_opacity yes
background_opacity 0.75

# Hide Title Bar
hide_window_decorations yes

# Keyboard Shortcuts
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
mouse_map middle release ungrabbed paste_from_selection
mouse_map left press ungrabbed mouse_selection normal
mouse_map left doublepress ungrabbed mouse_selection word
mouse_map left triplepress ungrabbed mouse_selection line


allow_remote_control yes
kitty_graphics on
