cursor            #cfbdfe
cursor_text_color #35275d

foreground            #e6e1e9
background            #0f0d13
selection_foreground  #332d41
selection_background  #cbc2dc
url_color             #cbc2dc

#: black 000000 767676
color0  #141218
color8  #36343a
#: red cc0403 f2201f
color1  #983568
color9  #d88eb4
#: green 19cb00 23fd00
color2  #cbc2dc
color10 #e8def8
#: yellow cecb00 fffd00
color3  #efb8c8
color11 #ffd9e3
#: blue 0d73cc 1a8fff
color4  #4c3e75
color12 #cfbdfe
#: magenta cb1ed1 fd28ff
color5  #4a4458
color13 #cbc2dc
#: cyan 0dcdcd 14ffff
color6  #633b49
color14 #efb8c8
#: white dddddd ffffff
color7  #cac4cf
color15 #e6e1e9

mark1_foreground #201047
mark1_background #e8ddff
mark2_foreground #1e192b
mark2_background #e8def8
mark3_foreground #31101d
mark3_background #ffd9e3

active_tab_foreground #35275d
active_tab_background #cfbdfe
inactive_tab_foreground #e8ddff
inactive_tab_background #4c3e75

active_border_color #cfbdfe
inactive_border_color #35275d
# bell_border_color #ff5a00
