cursor            #ffb2bf
cursor_text_color #561d2b

foreground            #f0dee0
background            #140c0d
selection_foreground  #43292e
selection_background  #e4bdc2
url_color             #e4bdc2

#: black 000000 767676
color0  #191112
color8  #3c3234
#: red cc0403 f2201f
color1  #983568
color9  #d88eb4
#: green 19cb00 23fd00
color2  #e4bdc2
color10 #ffd9de
#: yellow cecb00 fffd00
color3  #ebbe90
color11 #ffddbb
#: blue 0d73cc 1a8fff
color4  #713341
color12 #ffb2bf
#: magenta cb1ed1 fd28ff
color5  #5c3f44
color13 #e4bdc2
#: cyan 0dcdcd 14ffff
color6  #5f401d
color14 #ebbe90
#: white dddddd ffffff
color7  #d6c2c4
color15 #f0dee0

mark1_foreground #3a0716
mark1_background #ffd9de
mark2_foreground #2c1519
mark2_background #ffd9de
mark3_foreground #2b1700
mark3_background #ffddbb

active_tab_foreground #561d2b
active_tab_background #ffb2bf
inactive_tab_foreground #ffd9de
inactive_tab_background #713341

active_border_color #ffb2bf
inactive_border_color #561d2b
# bell_border_color #ff5a00
