context.modules = [
    {   name = libpipewire-module-access
        args = {
            access.allow = [
                { application = "pactl" }
                { application = "pipewire-pulse" }
            ]
        }
    }
]
