# #!/usr/bin/env bash
# PIPE="/tmp/qs_bt_wait_$$.fifo"
# mkfifo "$PIPE" 2>/dev/null
# trap 'rm -f "$PIPE"; kill $(jobs -p) 2>/dev/null; exit 0' EXIT INT TERM
# LC_ALL=C dbus-monitor --system "type='signal',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',arg0='org.bluez.Device1'" 2>/dev/null | grep --line-buffered 'string "Connected"' > "$PIPE" &
# LC_ALL=C dbus-monitor --system "type='signal',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',arg0='org.bluez.Adapter1'" 2>/dev/null | grep --line-buffered 'string "Powered"' > "$PIPE" &
# read -r _ < "$PIPE"



#!/usr/bin/env bash                                                              # Shebang line that tells the system to execute this script using the bash interpreter found in the user's PATH environment variable (more portable than hardcoding /bin/bash)
PIPE="/tmp/qs_bt_wait_$$.fifo"                                                  # Creates a variable PIPE containing a unique named pipe path using $$ (the current shell's process ID) to avoid conflicts with multiple script instances, prefixing with qs_bt_wait_ to identify it belongs to the QuickShell Bluetooth waiter component
mkfifo "$PIPE" 2>/dev/null                                                     # Creates the named pipe (FIFO special file) at the path specified by PIPE; 2>/dev/null suppresses error messages if the pipe already exists from a previous crashed instance of this script
trap 'rm -f "$PIPE"; kill $(jobs -p) 2>/dev/null; exit 0' EXIT INT TERM        # Sets up a trap that executes cleanup when the script exits normally (EXIT), receives an interrupt signal (INT, like Ctrl+C), or receives a termination signal (TERM); the cleanup commands forcefully remove the named pipe, kill all background jobs spawned by this script (suppressing errors if there are none), and exit with status code 0
LC_ALL=C dbus-monitor --system "type='signal',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',arg0='org.bluez.Device1'" 2>/dev/null | grep --line-buffered 'string "Connected"' > "$PIPE" &  # Sets C locale for consistent output, monitors the system D-Bus bus for PropertiesChanged signals specifically from BlueZ Device1 interfaces (individual Bluetooth devices like headphones, speakers, etc.), suppresses errors, pipes the signal stream through grep which filters for lines containing the string 'string "Connected"' (the property change indicating a device connected or disconnected) using line-buffered mode for immediate output, redirects matches to the named pipe, and runs this monitoring pipeline in the background (&)
LC_ALL=C dbus-monitor --system "type='signal',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',arg0='org.bluez.Adapter1'" 2>/dev/null | grep --line-buffered 'string "Powered"' > "$PIPE" &  # Sets up a second background D-Bus monitor that watches the system bus for PropertiesChanged signals from BlueZ Adapter1 interfaces (the Bluetooth adapter itself), suppresses errors, filters for lines containing 'string "Powered"' (the property change indicating the adapter being turned on or off) using line-buffered grep for instant delivery, and redirects matches to the same named pipe; this runs concurrently with the first monitor in the background (&)
read -r _ < "$PIPE"                                                             # Reads one line from the named pipe into the throwaway variable _ (underscore convention), using -r to prevent backslash interpretation; this command blocks the script execution until data is written to the pipe by either of the two D-Bus monitors (meaning either a device connection change or an adapter power state change occurred), at which point the script unblocks and exits, signaling the caller to refresh Bluetooth information